worker_processes  1;	# we will be giving 1 cores to each gateway
events {
    worker_connections  1024;
}

http {
    # Point Nginx's async resolver to Docker's internal DNS,
    #  otherwise it cannot resolve the name of other containers
    resolver 127.0.0.11 ipv6=off;

    server {
        listen 80;
        
        # Endpoint to purchase a ticket
        location /buy {
            default_type application/json;
            
            content_by_lua_block {
                local cjson = require "cjson"
                local redis = require "resty.redis"
                local red = redis:new()
                
                -- 1 second timeout for connecting, sending, and reading
                red:set_timeouts(1000, 1000, 1000) 
                
                -- Connect to our Redis container via the Docker network
                local ok, err = red:connect("redis-server-test", 6379)
                if not ok then
		    ngx.log(ngx.ERR, "Failed to connect to Redis: ", err)
                    ngx.status = 500
                    ngx.say(cjson.encode({error = "Failed to connect to Redis database"}))
                    return
                end
                
                -- Extract the tracking ID. For this test, we read it from the URL query parameters
                local args = ngx.req.get_uri_args()
                local ticket_id = args.ticket_id
                
                if not ticket_id then
                    ngx.status = 400
                    ngx.say(cjson.encode({error = "Missing ticket_id parameter"}))
                    return
                end
                
                -- Execute the Redis function
                local res, err = red:fcall("buy_ticket", 2, "purchased_tracking_ids", "tickets-counter", ticket_id)
                
                if not res then
		    ngx.log(ngx.ERR, "FCALL execution error: ", err)
                    ngx.status = 500
                    ngx.say(cjson.encode({error = "Database execution error executing buy_ticket operation"}))
                    return
                end
                
                -- Translate Redis integer response to HTTP Status Codes and JSON
                if res == -1 then
                    ngx.status = 409 -- HTTP 409 Conflict
                    ngx.say(cjson.encode({status = "error", message = "Ticket already purchased with this ID"}))
                elseif res == -2 then
                    ngx.status = 410 -- HTTP 410 Gone
                    ngx.say(cjson.encode({status = "error", message = "Tickets sold out"}))
                else
                    ngx.status = 200 -- HTTP 200 OK
                    ngx.say(cjson.encode({status = "success", ticket_number = res}))
                end
                
                -- Place the connection back into the connection pool
                red:set_keepalive(10000, 100)	-- 100 connections pool; 10 seconds connections
            }
        }
    }
}
