events { worker_connections 4096; }
http {
    upstream gateways {
        # Pointing to the Private IPs of Control Nodes 2 and 3
        server 10.0.1.136:80;
        server 10.0.1.201:80;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://gateways;
        }
    }
}
