worker_processes 1;
events {
    worker_connections 1024;
}

http {
    # Define the API Gateway cluster
    upstream gateway_cluster {
        # By default, Nginx uses a Round Robin algorithm
        server openresty-gateway-1:80;
        server openresty-gateway-2:80;
    }

    server {
        listen 80;

        location / {
            # Forward all incoming traffic to the upstream cluster
            proxy_pass http://gateway_cluster;
            
            # Pass original client information to the gateways
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
